### ISSUE TITLE
'module' object has no attribute 'SOL_TYPE_DUST_NOTIFHEALTHREPORT'

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#101]
```
CRASH

=== exception type ===
<type 'exceptions.AttributeError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 300, in _handler_dust_notifs
    timestamp   = int(time.time()), # TODO get timestamp of when data was created
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 99, in dust_to_json
    (sol_type, sol_ts, sol_value) = self._dust_notif_to_sol_json(d_n)
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 659, in _dust_notif_to_sol_json
    (sol_type, sol_value) = self._dust_other_notif_to_sol_json(dust_notif)
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 771, in _dust_other_notif_to_sol_json
    sol_type        = getattr(SolDefines, sol_typeName)
AttributeError: 'module' object has no attribute 'SOL_TYPE_DUST_NOTIFHEALTHREPORT'
```

**Comment by keomabrun** [comment]
Message received when error occured
```
{'fields': OrderedDict([('macAddress', '00-17-0d-00-00-58-eb-67'), ('payload', [145, 77, 1, 75, 174, 0, 8, 0, 0, 172, 0, 11, 0, 0, 171, 0, 12, 0, 0, 189, 0, 8, 0, 0, 172, 0, 7, 0, 1, 173, 0, 18, 0, 0, 171, 0, 11, 0, 0, 177, 0, 9, 0, 0, 172, 0, 10, 0, 0, 171, 0, 25, 0, 0, 176, 0, 3, 0, 0, 173, 0, 15, 0, 0, 170, 0, 9, 0, 0, 169, 0, 15, 0, 0, 175, 0, 4, 0, 0])]), 'manager': '/dev/ttyUSB3', 'name': 'notifHealthReport'}
```
