### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#111]
This error occurred in the Botanical Garden manager.
```
Traceback (most recent call last):
  File "solmanager.py", line 646, in _doSnapshot
    if resp['RC'] != 0:
KeyError: 'RC'
```

**Comment by keomabrun** [comment]
```
{u'body': u'internal server error', u'exception': u'Connection Error: no HDLC module, did I just disconnect?', u'traceback': u'Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
return route.call(**args)
File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
rv = callback(*a, **ka)
File "JsonServer.py", line 246, in _webhandle_raw_POST
return self.jsonManager.raw_POST(commandArray, fields, manager)
File "/root/smartmeshsdk/app/JsonServer/../../libs/SmartMeshSDK/utils/JsonManager.py", line 245, in raw_POST
fields       = fields,
File "/root/smartmeshsdk/app/JsonServer/../../libs/SmartMeshSDK/SerialConnector/SerialConnector.py", line 101, in send
return self._sendInternal(cmdId,False,serializedFields)
File "/root/smartmeshsdk/app/JsonServer/../../libs/SmartMeshSDK/SerialConnector/SerialConnector.py", line 169, in _sendInternal
raise ConnectionError(output)\nConnectionError: Connection Error: no HDLC module, did I just disconnect?\n'}
```

**Comment by keomabrun** [comment]
Must be related to #119 .
