### ISSUE TITLE
KeyError: 'numNbrs'

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#121]
Appeared at the Botanical Garden
```
Sat, 02 Sep 2017 16:58:27 UTC

CRASH
Thread PubServerThread!

=== exception type ===
<type 'exceptions.KeyError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 113, in run
    self._doSomething()
  File "solmanager.py", line 316, in _doSomething
    self._publishNow()
  File "solmanager.py", line 402, in _publishNow
    solBinObjectsToPublish.append(self.sol.json_to_bin(o))
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 170, in json_to_bin
    sol_json['value']
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 980, in _get_sol_binary_value_snapshot
    mote['numNbrs'],                            # INT8U   B
KeyError: 'numNbrs'
```

**Comment by keomabrun** [comment]
This occurred as well on EVA_lab
