### ISSUE TITLE
Serial Connection error

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#128]
The error we were seeing on the Metronome Manager finally showed up on a Raspberry Pi.

```
Traceback (most recent call last):
  File "solmanager.py", line 687, in _doSnapshot
    "pathId":     currentPathId
  File "solmanager.py", line 230, in issueRawApiCommand
    fields           = fields,
  File "/home/pi/solmanager/../smartmeshsdk/libs/SmartMeshSDK/utils/JsonManager.py", line 245, in raw_POST
    fields       = fields,
  File "/home/pi/solmanager/../smartmeshsdk/libs/SmartMeshSDK/SerialConnector/SerialConnector.py", line 101, in send
    return self._sendInternal(cmdId,False,serializedFields)
  File "/home/pi/solmanager/../smartmeshsdk/libs/SmartMeshSDK/SerialConnector/SerialConnector.py", line 185, in _sendInternal
    raise ConnectionError(output)
ConnectionError: Connection Error: retried 5 times, max allowed is 5
```

**Comment by keomabrun** [comment]
I appeared while the solserver was off for a couple of hours. I then recovered.

**Comment by zhangziran-ucb** [comment]
It then recovered automatically? or you restarted the script?

**Comment by keomabrun** [comment]
It recovered automatically.

**Comment by twatteyne** [comment]
:-( good catch, though
