### ISSUE TITLE
crash report ! metronome manager on fifth floor!

### ISSUE THREAD

**Issue by zhangziran-ucb** [realms-team/solmanager#134]
CRASH
=== exception type ===
<type 'exceptions.KeyError'>
=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 175, in _handler_dust_notifs
    timestamp   = epoch,
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 99, in dust_to_json
    (sol_type, sol_ts, sol_value) = self._dust_notif_to_sol_json(d_n)
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 657, in _dust_notif_to_sol_json
    (sol_type, sol_value) = self._dust_oap_to_sol_json(dust_notif)
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 751, in _dust_oap_to_sol_json
    'input':   dust_notif['fields']['input'],
KeyError: 'input'

**Comment by keomabrun** [comment]
dust_notif trace:
```
{'fields': {'packet_timestamp': (263519292160L, 2781185), 'channel_str': 'digital_in/D0', 'received_timestamp': '2017-12-13 10:49:36.367089', 'channel': [2, 0], 'new_val': 1}, 'mac': '00-17-0d-00-00-58-fe-43', 'name': 'oap'}
```
