### ISSUE TITLE
Error when config missing in config file.

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#70]
The following error occur when the line `pullperiodminutes   = XX` is missing on the solmanager.config file. This should not happen as the default config is loaded instead.

Traceback (most recent call last):
  File "solmanager.py", line 1584, in <module>
    configs[config_name] = cf_parser.getint('config', config_name)
  File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 700, in _interpolate_some
    p = rest.find("%")
AttributeError: 'int' object has no attribute 'find'

**Comment by keomabrun** [comment]
Fixed. We are now raising a keyerror if any config field is missing. Is it sufficiently explicit.
