### ISSUE TITLE
ConnectionError causes solmanager to crash

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#86]
The following error occurs and the manager does not restarts.
Appeared in Junin with solmanager and sol in version 1.0.0.0

=============================================================
Sat, 01 Oct 2016 06:52:40 UTC
  
CRASH in Thread SendThread!
  
=== exception type ===
<class 'requests.exceptions.ConnectionError'>
  
=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 723, in run
    self.publishNow()
  File "solmanager.py", line 823, in publishNow
    verify  = self.solserver_cert,
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 105, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
  
Exception in thread SolManager:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "solmanager.py", line 1452, in run
    self.close()
  File "solmanager.py", line 1478, in close
    t.close()
  File "solmanager.py", line 1050, in close
    self.web.server.stopserver()
  File "solmanager.py", line 986, in stopserver
    self.server.stop()
  File "/home/pi/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2170, in stop
    self.requests.stop(self.shutdown_timeout)
  File "/home/pi/.local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1642, in stop
    worker = self._threads.pop()
IndexError: pop from empty list

**Comment by keomabrun** [comment]
Fixed with #88
