### ISSUE TITLE
unknown HR error

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#94]
Wed, 10 May 2017 22:37:34 UTC

CRASH in Thread DustThread!

=== exception type ===
<type 'exceptions.ValueError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 515, in _notifAll
    timestamp   = epoch,
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 97, in dust_to_json
    (sol_type,sol_ts,sol_value) = self._get_sol_json_fields(d_n)
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 638, in _get_sol_json_fields
    (sol_type,sol_value) = self._get_sol_json_value_dust_hr(dust_notif)
  File "/home/pi/solmanager/../sol/solobjectlib/Sol.py", line 858, in _get_sol_json_value_dust_hr
    hr = self.hrParser.parseHr(dust_notif.payload)
  File "/home/pi/solmanager/../sol/smartmeshsdk/libs/SmartMeshSDK/protocols/Hr/HrParser.py", line 112, in parseHr
    raise ValueError("unknown HR id {0}".format(id))
ValueError: unknown HR id 0

**Comment by keomabrun** [comment]
This issue was solved by: https://github.com/realms-team/sol/issues/63
