### ISSUE TITLE
Reimplement smartmeshipapi_POST

### ISSUE THREAD

**Issue by keomabrun** [realms-team/solmanager#96]

**Comment by keomabrun** [comment]
CRASH
```
Thread JsonThread!

=== exception type ===
<type 'exceptions.AttributeError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 1014, in _webhandler_smartmeshipapi_POST
    res = self.mgrThread.handler_smartmeshipapi_POST(bottle.request.json)
AttributeError: 'MgrThreadSerial' object has no attribute 'handler_smartmeshipapi_POST'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "solmanager.py", line 1014, in _webhandler_smartmeshipapi_POST
    res = self.mgrThread.handler_smartmeshipapi_POST(bottle.request.json)
AttributeError: 'MgrThreadSerial' object has no attribute 'handler_smartmeshipapi_POST'
```
